In [ ]:
#1.What are the types of Applications?

#Applications, or software applications, can be classified into several types based on their purpose,
#platform, and technology used. Here’s an overview of the main types of applications:


In [ ]:
#2.What is programing?
#Python programming is the process of creating software applications using the Python language, known for its simple syntax, readability, and versatility.

In [ ]:
#3.What is Python?
#Python is like giving instructions to a computer using simple English words.
#Python is a very easy and powerful programming language used to tell computers what to do.

In [ ]:
#4.Write a Python program to check if a number is positive, negative or zero.
num = int(input("Enter a Number:"))

if num > 0:
  print(f"{num} Is  Positive")
elif num <0:
  print(f"{num} Is  Negative")
else:
  print(f"{num} Is  Zero")



Enter a Number:5
5 Is  Positive


In [ ]:
#5. Write a Python program to get the Factorial number of given numbers. ?
# Find factorial of a number using loop

num = int(input("Enter a number: "))
factorial = 1

if num < 0:
    print("Factorial is not defined for negative numbers.")
elif num == 0:
    print("The factorial of 0 is 1.")
else:
    for i in range(1, num + 1):
        factorial *= i
    print(f"The factorial of {num} is {factorial}")


Enter a number: 5
The factorial of 5 is 120


In [ ]:
#6. Write a Python program to get the Fibonacci series of given range.?
n = int(input("Enter the number of terms: "))

a, b = 0, 1

if n <= 0:
    print("Please enter a positive integer.")
elif n == 1:
    print("Fibonacci sequence up to 1 term:")
    print(a)
else:
    print("Fibonacci sequence:")
    for i in range(n):
        print(a, end=" ")
        a, b = b, a + b


Enter the number of terms: 5
Fibonacci sequence:
0 1 1 2 3 

In [ ]:
#7. How memory is managed in Python?
import gc
print(gc.isenabled())
gc.collect()

a = [1,2,3,4,5]
b = a
del a
print(b)

True
[1, 2, 3, 4, 5]


In [ ]:
#8. What is the purpose continuing statement in python?
#The continue statement is used inside loops (like for or while) to skip the current iteration and move to the next iteration of the loop.
#To skip part of the loop when a certain condition is met, and continue with the next cycle without exiting the loop.


In [ ]:
#9. Write python program that swap two number with temp variable and

a = int(input("Enter first number (a): "))
b = int(input("Enter second number (b): "))
temp = a
a = b
b = temp

print("After swapping:")
print("a =", a)
print("b =", b)


Enter first number (a): 5
Enter second number (b): 5
After swapping:
a = 5
b = 5


In [ ]:
#9.Write python program that swap two number without temp variable.
a = int(input("Enter first number (a): "))
b = int(input("Enter second number (b): "))

a, b = b, a

print("After swapping:")
print("a =", a)
print("b =", b)


Enter first number (a): 5
Enter second number (b): 5
After swapping:
a = 5
b = 5


In [ ]:
#10. Write a Python program to find whether a given number is even or odd, print out an appropriate message to the user.
# Program to check if a number is even or odd

x = int(input("Enter a number: "))
if x % 2 == 0:
    print(f"{x} is an Even number.")
else:
    print(f"{x} is an Odd number.")


Enter a number: 5
5 is an Odd number.


In [ ]:
#11. Write a Python program to test whether a passed letter is a vowel or not.
letter = input("Enter a single letter: ")

letter = letter.lower()
if len(letter) == 1 and letter.isalpha():
    if letter in ['a', 'e', 'i', 'o', 'u']:
        print(f"{letter} is a Vowel.")
    else:
        print(f"{letter} is Not a Vowel.")
else:
    print("Please enter a single alphabet letter only.")


Enter a single letter: a
a is a Vowel.


In [ ]:
#12. Write a Python program to sum of three given integers. However, if two values are equal sum will be zero.

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))
if a == b or b == c or a == c:
    print("Two values are equal. Sum is 0.")
    sum = 0
else:
    sum = a + b + c
    print("Sum of three different numbers is:", sum)


Enter first number: 5
Enter second number: 7
Enter third number: 5
Two values are equal. Sum is 0.


In [ ]:
#13. Write a Python program that will return true if the two given integer values are equal or their sum or difference is 5.
def check_numbers(a, b):
    if a == b or (a + b == 5) or (abs(a - b) == 5):
        return True
    else:
        return False

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("Result:", check_numbers(a, b))

Enter first number: 5
Enter second number: 7
Result: False


In [ ]:
#14. Write a python program to sum of the first n positive integers.
n = int(input("Enter a positive integer: "))

if n > 0:
    total = 0
    for i in range(1, n + 1):
        total += i

    print(f"The sum of the first {n} positive integers is: {total}")
else:
    print("Please enter a positive number greater than 0.")


Enter a positive integer: 5
The sum of the first 5 positive integers is: 15


In [ ]:
#15. Write a Python program to calculate the length of a string.
user_string = input("Enter a string: ")
length = len(user_string)
print("The length of the string is:", length)

Enter a string: Hello World
The length of the string is: 11


In [ ]:
#16. Write a Python program to count the number of characters (character frequency) in a string
text = input("Enter a string: ")

char_freq = {}

for char in text:
    if char in char_freq:
        char_freq[char] += 1
    else:
        char_freq[char] = 1

print("Character frequency:")
for char, freq in char_freq.items():
    print(f"'{char}': {freq}")

Enter a string: Hello
Character frequency:
'H': 1
'e': 1
'l': 2
'o': 1


In [ ]:
#17. What are negative indexes and why are they used?
fruits = ['apple', 'banana', 'cherry', 'date']

print(fruits[-1])
print(fruits[-2])

date
cherry


In [ ]:
#18. Write a Python program to count occurrences of a substring in a string.
main_string = input("Enter the main string: ")
substring = input("Enter the substring to count: ")
count = main_string.count(substring)
print(f"The substring '{substring}' appears {count} times in the string.")

Enter the main string: Hello World,Hello Again
Enter the substring to count: Hello
The substring 'Hello' appears 2 times in the string.


In [ ]:
#19. Write a Python program to count the occurrences of each word in a given sentance?
sentence = input("Enter a sentence: ")
sentence = sentence.lower()
words = sentence.split()
word_count = {}

for word in words:
    if word in word_count:
        word_count[word] += 1
    else:
        word_count[word] = 1

print("Word frequencies:")
for word, count in word_count.items():
    print(f"'{word}': {count}")


Enter a sentence: this is yusuf , this is only yusuf
Word frequencies:
'this': 2
'is': 2
'yusuf': 2
',': 1
'only': 1


In [ ]:
#20.Write a Python program to get a single string from two given strings, separated by a space and swap the first two characters of each string.
str1 = input("Enter first string: ")
str2 = input("Enter second string: ")

if len(str1) >= 2 and len(str2) >= 2:
    # Swap first two characters
    new_str1 = str2[:2] + str1[2:]
    new_str2 = str1[:2] + str2[2:]
    result = new_str1 + " " + new_str2
    print("Result:", result)
else:
    print("Both strings should have at least two characters.")


Enter first string: Hello
Enter second string: World
Result: Wollo Herld


In [ ]:
#21. Write a Python program to add 'in' at the end of a given string (length should be at least 3). If the given string already ends with 'ing' then add 'ly' instead if the string length of the given string is less than 3, leave it unchanged.
word = input("Enter a word: ")

if len(word) < 3:
    result = word
elif word.endswith('ing'):
    result = word + 'ly'
else:
    result = word + 'ing'
print("Modified word:", result)

Enter a word: Read
Modified word: Reading


In [ ]:
#22. Write a Python function to reverses a string if its length is a multiple of 4.
def reverse_if_multiple_of_4(text):
    if len(text) % 4 == 0:
        return text[::-1]
    else:
        return text
input_str = input("Enter a string: ")
result = reverse_if_multiple_of_4(input_str)
print("Result:", result)

Enter a string: text
Result: txet


In [ ]:
#23.Write a Python program to get a string made of the first 2 and the last 2 chars from a given a string. If the string length is less than 2, return instead of the empty string.
text = input("Enter a string: ")
if len(text) < 2:
    result = ""
else:
    result = text[:2] + text[-2:]

print("Result:", result)

Enter a string: Python
Result: Pyon


In [ ]:
#24. Write a Python function to insert a string in the middle of a string.
def insert_middle(original, insert):
    mid = len(original) // 2
    result = original[:mid] + insert + original[mid:]
    return result

str1 = input("Enter the original string: ")
str2 = input("Enter the string to insert: ")

result = insert_middle(str1, str2)
print("Result:", result)

Enter the original string: KhanKhan
Enter the string to insert: Yusuf
Result: KhanYusufKhan


In [ ]:
#25.What is List? How will you reverse a list?
my_list = [10, 20, 30, 40, 50]
print(my_list[0])

my_list.reverse()
print(my_list)

10
[50, 40, 30, 20, 10]


In [ ]:
#26.How will you remove last object from a list?
my_list = [10, 20, 30, 40]
my_list.pop()
print(my_list)

[10, 20, 30]


In [ ]:
#27.Suppose list1 is [2, 33, 222, 14, and 25], what is list1 [-1]?
list1 = [2, 33, 222, 14, 25]
list1[-1]

25

In [ ]:
#28.Differentiate between append () and extend () methods?
#append
list1 = [1, 2, 3]
list1.append([4, 5])
print(list1)
#Extend
list2 = [1, 2, 3]
list2.extend([4, 5])
print(list2)

[1, 2, 3, [4, 5]]
[1, 2, 3, 4, 5]


In [ ]:
#29.Write a Python function to get the largest number, smallest num and sum of all from a list.
def analyze_list(numbers):
    if not numbers:
        return "List is empty."

    largest = max(numbers)
    smallest = min(numbers)
    total_sum = sum(numbers)

    return f"Largest: {largest}, Smallest: {smallest}, Sum: {total_sum}"

my_list = [5, 12, 7, 3, 18, 9]
result = analyze_list(my_list)
print(result)

TypeError: 'int' object is not callable

In [ ]:
#30.How will you compare two lists?
list1 = [1, 2, 3]
list2 = [1, 2, 3]

print(list1 == list2)

True


In [ ]:
#31.Write a Python program to count the number of strings where the string length is 2 or more and the first and last character are same from a given list of strings.
def count_matching_strings(strings):
    count = 0
    for s in strings:
        if len(s) >= 2 and s[0] == s[-1]:
            count += 1
    return count
string_list = ['abc', 'xyz', 'aba', '1221', 'aa', 'a', 'madam']

result = count_matching_strings(string_list)
print("Number of matching strings:", result)

Number of matching strings: 4


In [ ]:
#32.Write a Python program to remove duplicates from a list.
def remove_duplicates(input_list):
    return list(set(input_list))
my_list = [1, 2, 2, 3, 4, 4, 5, 1]
result = remove_duplicates(my_list)
print("List after removing duplicates:", result)

List after removing duplicates: [1, 2, 3, 4, 5]


In [ ]:
#33.Write a Python program to check a list is empty or not.
def check_list_empty(input_list):
    if not input_list:
        print("The list is empty.")
    else:
        print("The list is not empty.")

my_list = []
check_list_empty(my_list)

The list is empty.


In [ ]:
#34. Write a Python function that takes two lists and returns true if they have at least one common member.
def have_common_member(list1, list2):
    for item in list1:
        if item in list2:
            return True
    return False
a = [1, 2, 3, 4]
b = [5, 6, 3, 8]
print(have_common_member(a, b))

True


In [ ]:
#35.Write a Python program to generate and print a list of first and last 5 elements where the values are square of numbers between 1 and 30.

squares = [x**2 for x in range(1, 31)]
print("First 5 elements:", squares[:5])
print("Last 5 elements:", squares[-5:])

First 5 elements: [1, 4, 9, 16, 25]
Last 5 elements: [676, 729, 784, 841, 900]


In [ ]:
#36.Write a Python function that takes a list and returns a new list with unique elements of the first list.
def unique_elements(input_list):
    return list(set(input_list))
my_list = [1, 2, 2, 3, 4, 4, 5]
print(unique_elements(my_list))

[1, 2, 3, 4, 5]


In [ ]:
#37.Write a Python program to convert a list of characters into a string.
def list_to_string(char_list):
    return ''.join(char_list)
chars = ['H', 'e', 'l', 'l', 'o']
result = list_to_string(chars)
print(result)

Hello


In [ ]:
#38.Write a Python program to select an item randomly from a list.
import random

def select_random_item(my_list):
    return random.choice(my_list)
items = ['apple', 'banana', 'cherry', 'date', 'elderberry']
random_item = select_random_item(items)
print("Randomly selected item:", random_item)

Randomly selected item: apple


In [ ]:
#39.Write a Python program to find the second smallest number in a list.
def second_smallest(numbers):
    unique_numbers = list(set(numbers))
    if len(unique_numbers) < 2:
        return None
    unique_numbers.sort()
    return unique_numbers[1]
my_list = [4, 1, 7, 1, 3, 9]
print("Second smallest number:", second_smallest(my_list))

Second smallest number: 3


In [ ]:
#40.Write a Python program to get unique values from a list
def get_unique_values(my_list):
    return list(set(my_list))
numbers = [1, 2, 2, 3, 4, 4, 5]
unique = get_unique_values(numbers)
print("Unique values:", unique)

Unique values: [1, 2, 3, 4, 5]


In [ ]:
#41.Write a Python program to check whether a list contains a sub list
def contains_sublist(main_list, sub_list):
    sub_len = len(sub_list)
    for i in range(len(main_list) - sub_len + 1):
        if main_list[i:i + sub_len] == sub_list:
            return True
    return False
main = [1, 2, 3, 4, 5]
sub = [3, 4]

result = contains_sublist(main, sub)
print("Sublist found?" , result)

Sublist found? True


In [ ]:
#42.Write a Python program to split a list into different variables.
my_list = [10, 20, 30]

a, b, c = my_list

print("a =", a)
print("b =", b)
print("c =", c)

a = 10
b = 20
c = 30


In [ ]:
#43.What is tuple? Difference between list and tuple.
#Answer:A tuple is an ordered, immutable collection of elements.
#It can hold multiple data types like integers, strings, lists, etc.

#Syntax	 = my_list = [1, 2, 3] , 	my_tuple = (1, 2, 3)
#Mutable = list: can be changed	, Tuple : cannot be changed
#Methods = 	List: More methods (append, etc.), Tuple:	Fewer methods
#Performance = List: Slower	, Tuple: Faster (due to immutability)
#Use case = List:	When data may change , Tuple:	When data should stay fixed
#Memory	= List : Uses more memory , Tuple : 	Uses less memory
my_tuple = (1, 2, 3)
print(my_tuple)

(1, 2, 3)


In [ ]:
#44. Write a Python program to create a tuple with different data types.

my_tuple = (42, "Hello", 3.14, True, [1, 2, 3], {'a': 1, 'b': 2})

print("Tuple with different data types:")
print(my_tuple)

Tuple with different data types:
(42, 'Hello', 3.14, True, [1, 2, 3], {'a': 1, 'b': 2})


In [ ]:
#45.Write a Python program to unzip a list of tuples into individual lists.
list_of_tuples = [("a", 1), ("b", 2), ("c", 3)]

list1, list2 = zip(*list_of_tuples)
list1 = list(list1)
list2 = list(list2)

print("List 1:", list1)
print("List 2:", list2)

List 1: ['a', 'b', 'c']
List 2: [1, 2, 3]


In [ ]:
#46.Write a Python program to convert a list of tuples into a dictionary.
list_of_tuples = [("a", 1), ("b", 2), ("c", 3)]

dictionary = dict(list_of_tuples)
print("Dictionary:", dictionary)

Dictionary: {'a': 1, 'b': 2, 'c': 3}


In [ ]:
#47.How will you create a dictionary using tuples in python?
tuple_list = [("name", "Alice"), ("age", 25), ("city", "Delhi")]

my_dict = dict(tuple_list)

print(my_dict)

{'name': 'Alice', 'age': 25, 'city': 'Delhi'}


In [ ]:
#48.Write a Python script to sort (ascending and descending) a dictionary by value?
my_dict = {'apple': 10, 'banana': 5, 'cherry': 20, 'date': 15}
asc_sorted = dict(sorted(my_dict.items(), key=lambda item: item[1]))
desc_sorted = dict(sorted(my_dict.items(), key=lambda item: item[1], reverse=True))

print("Ascending Order:", asc_sorted)
print("Descending Order:", desc_sorted)

Ascending Order: {'banana': 5, 'apple': 10, 'date': 15, 'cherry': 20}
Descending Order: {'cherry': 20, 'date': 15, 'apple': 10, 'banana': 5}


In [ ]:
#49.Write a Python script to concatenate following dictionaries to create a new one.
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
dict3 = {'e': 5, 'f': 6}

new_dict = {}
for d in (dict1, dict2, dict3):
    new_dict.update(d)

print("Concatenated Dictionary:", new_dict)
combined_dict = {**dict1, **dict2, **dict3}
print("Combined Dictionary (Unpacking):", combined_dict)

Concatenated Dictionary: {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}
Combined Dictionary (Unpacking): {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}


In [ ]:
#50.Write a Python script to check if a given key already exists in a dictionary.

my_dict = {'name': 'Alice', 'age': 25, 'city': 'Delhi'}


key_to_check = 'age'

if key_to_check in my_dict:
    print(f"Key '{key_to_check}' exists in the dictionary.")
else:
    print(f"Key '{key_to_check}' does NOT exist in the dictionary.")

Key 'age' exists in the dictionary.


In [ ]:
#51.How Do You Traverse Through a Dictionary Object in Python?
my_dict = {'name': 'Alice', 'age': 25, 'city': 'Delhi'}

for key in my_dict:
    print("Key:", key, "Value:", my_dict[key])


Key: name Value: Alice
Key: age Value: 25
Key: city Value: Delhi


In [ ]:
#52.How Do You Check the Presence of a Key in A Dictionary?
my_dict = {'name': 'Alice', 'age': 25, 'city': 'Delhi'}

key = 'age'

if key in my_dict:
    print(f"Key '{key}' is present in the dictionary.")
else:
    print(f"Key '{key}' is NOT present in the dictionary.")

Key 'age' is present in the dictionary.


In [ ]:
#53.Write a Python script to print a dictionary where the keys are numbers between 1 and 15.
my_dict = {x: x**2 for x in range(1, 16)}
print("Dictionary with keys from 1 to 15 and squared values:")
print(my_dict)

Dictionary with keys from 1 to 15 and squared values:
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}


In [ ]:
#54.Write a Python program to check multiple keys exists in a dictionary
my_dict = {'name': 'Alice', 'age': 25, 'city': 'Delhi'}

keys_to_check = ['name', 'age']
if all(key in my_dict for key in keys_to_check):
    print("All keys exist in the dictionary.")
else:
    print("Some keys are missing in the dictionary.")

All keys exist in the dictionary.


In [ ]:
#55. Write a Python script to merge two Python dictionaries
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}

dict1.update(dict2)

print("Merged Dictionary:", dict1)

Merged Dictionary: {'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [ ]:
#56.Write a Python program to map two lists into a dictionary
#Sample output: Counter ({'a': 400, 'b': 400,’d’: 400, 'c': 300}).
from collections import Counter

keys = ['a', 'b', 'c', 'd']
values = [400, 400, 300, 400]

mapped_dict = dict(zip(keys, values))

result = Counter(mapped_dict)

print("Counter:", result)

Counter: Counter({'a': 400, 'b': 400, 'd': 400, 'c': 300})


In [ ]:
#57. Write a Python program to find the highest 3 values in a dictionary
my_dict = {'a': 100, 'b': 300, 'c': 250, 'd': 400, 'e': 150}

top_3 = sorted(my_dict.items(), key=lambda item: item[1], reverse=True)[:3]
print("Top 3 highest values in the dictionary:")
for key, value in top_3:
    print(f"{key}: {value}")

Top 3 highest values in the dictionary:
d: 400
b: 300
c: 250


In [ ]:
#58.Write a Python program to combine values in python list of dictionaries.
#Sample data: [{'item': 'item1', 'amount': 400}, {'item': 'item2', 'amount':
#300}, o {'item': 'item1', 'amount': 750}]
#Expected Output:
#• Counter ({'item1': 1150, 'item2': 300})

from collections import Counter

data = [
    {'item': 'item1', 'amount': 400},
    {'item': 'item2', 'amount': 300},
    {'item': 'item1', 'amount': 750}
]

result = Counter()

for entry in data:
    result[entry['item']] += entry['amount']
print("Counter:", result)

Counter: Counter({'item1': 1150, 'item2': 300})


In [ ]:
#59.Write a Python program to create a dictionary from a string.
#Note: Track the count of the letters from the string.

from collections import Counter
input_str = "hello world"

letter_count = Counter(char for char in input_str if char.isalpha())

print("Letter Count Dictionary:", dict(letter_count))


Letter Count Dictionary: {'h': 1, 'e': 1, 'l': 3, 'o': 2, 'w': 1, 'r': 1, 'd': 1}


In [ ]:
#60. Sample string:
#'w3resource' Expected output:
#• {'3': 1,’s’: 1, 'r': 2, 'u': 1, 'w': 1, 'c': 1, 'e': 2, 'o': 1}

from collections import Counter

sample_str = 'w3resource'

char_count = Counter(sample_str)

print(dict(char_count))

{'w': 1, '3': 1, 'r': 2, 'e': 2, 's': 1, 'o': 1, 'u': 1, 'c': 1}


In [ ]:
#61.Write a Python function to calculate the factorial of a number (a nonnegative integer)

def factorial(n):
    if n < 0:
        return "Factorial is not defined for negative numbers."

    result = 1
    for i in range(2, n + 1):
        result *= i
    return result

num = 5
print(f"Factorial of {num} is {factorial(num)}")

Factorial of 5 is 120


In [ ]:
#62. Write a Python function to check whether a number is in a given range

def is_in_range(number, start, end):
    if start <= number <= end:
        return True
    else:
        return False

num = 7
print(f"Is {num} in range 5 to 10? {is_in_range(num, 5, 10)}")

Is 7 in range 5 to 10? True


In [ ]:
#63.Write a Python function to check whether a number is perfect or not.

def is_perfect(number):
    if number <= 0:
        return False

    divisors_sum = 0
    for i in range(1, number):
        if number % i == 0:
            divisors_sum += i

    return divisors_sum == number

num = 28
if is_perfect(num):
    print(f"{num} is a perfect number.")
else:
    print(f"{num} is not a perfect number.")

28 is a perfect number.


In [ ]:
#64.Write a Python function that checks whether a passed string is palindrome or not
def is_palindrome(s):
    s = s.replace(" ", "").lower()
    return s == s[::-1]

text = "Madam"
if is_palindrome(text):
    print(f"'{text}' is a palindrome.")
else:
    print(f"'{text}' is not a palindrome.")

'Madam' is a palindrome.


In [ ]:
#65.How Many Basic Types of Functions Are Available in Python?
#answer : 1. Built-in Functions
#           2. User-defined Functions


In [ ]:
#66.How can you pick a random item from a list or tuple?
import random

my_list = [10, 20, 30, 40, 50]
random_item = random.choice(my_list)

print("Random item from list:", random_item)

Random item from list: 40


In [ ]:
#67.How can you pick a random item from a range?
my_range = range(1, 11)  # 1 to 10

random_item = random.choice(my_range)

print("Random item from range:", random_item)

Random item from range: 9


In [ ]:
#68.How can you get a random number in python?
num = random.randint(1, 100)
print("Random integer:", num)

Random integer: 93


In [ ]:
#69.How will you set the starting value in generating random numbers?
random.seed(10)

print(random.randint(1, 100))
print(random.random())

74
0.032585065282054626


In [ ]:
#70.How will you randomize the items of a list in place?
my_list = [1, 2, 3, 4, 5]
random.shuffle(my_list)
print("Shuffled list:", my_list)

Shuffled list: [3, 2, 5, 1, 4]


In [ ]:
#71.What is File function in python? What are keywords to create and write file.

#Answer = In Python, file functions allow you to create, open, read, write, and manipulate files.
#Python uses built-in functions to perform file operations, primarily through the open() function.
#open(),Read(),Write(),Writeline(),Readline(),Readlines(),Close(),With...

In [ ]:
#72.Write a Python program to read an entire text file.

with open("example.txt", "r") as file:
    content = file.read()

print(content)

FileNotFoundError: [Errno 2] No such file or directory: 'example.txt'

In [ ]:
#73.Write a Python program to append text to a file and display the text.
with open("example.txt", "a") as file:
    file.write("\nThis line is appended to the file.")

with open("example.txt", "r") as file:
    content = file.read()

print("File content after appending:")
print(content)


File content after appending:

This line is appended to the file.


In [ ]:
#74. Write a Python program to read first n lines of a file.
def read_first_n_lines(filename, n):
    with open(filename, 'r') as file:
        for i in range(n):
            line = file.readline()
            if not line:
                break
            print(line.strip())


read_first_n_lines("example.txt", 3)


This line is appended to the file.


In [ ]:
#75.Write a Python program to read last n lines of a file.
def read_last_n_lines(filename, n):
    with open(filename, 'r') as file:
        lines = file.readlines()
        last_lines = lines[-n:]
        for line in last_lines:
            print(line.strip())

read_last_n_lines("example.txt", 3)


This line is appended to the file.


In [ ]:
#76.Write a Python program to read a file line by line and store it into a list
def read_file_to_list(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()
        lines = [line.strip() for line in lines]
    return lines

file_lines = read_file_to_list("example.txt")
print("Lines stored in list:")
print(file_lines)

Lines stored in list:
['', 'This line is appended to the file.']


In [ ]:
#77. Write a Python program to read a file line by line store it into a variable.
def read_file_to_variable(filename):
    content = ""
    with open(filename, 'r') as file:
        for line in file:
            content += line
    return content

file_content = read_file_to_variable("example.txt")
print("File content stored in variable:")
print(file_content)

File content stored in variable:

This line is appended to the file.


In [ ]:
#78. Write a python program to find the longest words.

def find_longest_words(filename):
    with open(filename, 'r') as file:
        words = file.read().split()
        max_len = max(len(word) for word in words)
        longest_words = [word for word in words if len(word) == max_len]
    return longest_words

longest = find_longest_words("example.txt")
print("Longest word(s):")
for word in longest:
    print(word)

Longest word(s):
appended


In [ ]:
#79.Write a Python program to count the number of lines in a text file.
def count_lines_in_file(filename):
    with open(filename, 'r') as file:
        line_count = sum(1 for line in file)
    return line_count
lines = count_lines_in_file("example.txt")
print(f"Number of lines in the file: {lines}")

Number of lines in the file: 2


In [ ]:
#80.Write a Python program to count the frequency of words in a file.
from collections import Counter
import string

def count_word_frequency(filename):
    with open(filename, 'r') as file:
        text = file.read().lower()
        # Remove punctuation
        text = text.translate(str.maketrans('', '', string.punctuation))
        words = text.split()
        word_counts = Counter(words)
    return word_counts

frequencies = count_word_frequency("example.txt")
print("Word Frequencies:")
for word, count in frequencies.items():
    print(f"{word}: {count}")

Word Frequencies:
this: 1
line: 1
is: 1
appended: 1
to: 1
the: 1
file: 1


In [ ]:
#81. Write a Python program to write a list to a file.
def write_list_to_file(filename, data_list):
    with open(filename, 'w') as file:
        for item in data_list:
            file.write(str(item) + '\n')

my_list = ['apple', 'banana', 'cherry', 'date']
write_list_to_file("fruits.txt", my_list)

print("List written to file successfully.")

List written to file successfully.


In [ ]:
#82. Write a Python program to copy the contents of a file to another file.
def copy_file(source_file, destination_file):
    with open(source_file, 'r') as src:
        content = src.read()
    with open(destination_file, 'w') as dst:
        dst.write(content)

copy_file("example.txt", "copy_of_example.txt")
print("File copied successfully.")

File copied successfully.


In [ ]:
#83.Explain Exception handling? What is an Error in Python?

#Answer = In Python, an error is a problem in the program that causes it to stop execution. Errors are broadly categorized into:
#1. Syntax Errors, 2. Runtime Errors (Exceptions)

try:
    x = 10 / 0
except ZeroDivisionError:
    print("You can't divide by zero!")
finally:
    print("Execution complete.")

You can't divide by zero!
Execution complete.


In [ ]:
#84.How many except statements can a try-except block have? Name Some built-in exception classes:
#answer =
try:
    x = int(input("Enter a number: "))
    y = 10 / x
except ValueError:
    print("You must enter a number!")
except ZeroDivisionError:
    print("Cannot divide by zero!")
except Exception as e:
    print("An unexpected error occurred:", e)

Enter a number: 5


In [ ]:
#85.When will the else part of try-except-else be executed?

try:
    num = int(input("Enter a number: "))
    result = 10 / num
except ZeroDivisionError:
    print("Cannot divide by zero!")
except ValueError:
    print("Invalid input! Enter a number.")
else:
    print("No exception occurred. Result is:", result)
finally:
    print("This will always run.")

Enter a number: 5
No exception occurred. Result is: 2.0
This will always run.


In [ ]:
#86.Can one block of except statements handle multiple exception?

try:
    num = int(input("Enter a number: "))
    result = 10 / num
except ValueError:
    print("Invalid input. Please enter a number.")
except ZeroDivisionError:
    print("Cannot divide by zero.")

Enter a number: 5


In [ ]:
#87.When is the finally block executed?
def test():
    try:
        print("In try block")
        x = 1 / 0
    except ZeroDivisionError:
        print("In except block")
        return
    finally:
        print("In finally block")

test()

In try block
In except block
In finally block


In [ ]:
#88.What happens when „1‟== 1 is executed?
type("1")
type(1)
"1" == 1


False

In [ ]:
#89.How Do You Handle Exceptions with Try/Except/Finally in Python?
try:
    f = open("data.txt", "r")
    num = int(f.readline())
    result = 10 / num
except FileNotFoundError:
    print("File not found.")
except ZeroDivisionError:
    print("Cannot divide by zero.")
except ValueError:
    print("Invalid number in file.")
finally:
    print("Closing the file.")
    try:
        f.close()
    except:
        pass


File not found.
Closing the file.


In [ ]:
#90.Write python program that user to enter only odd numbers, else will raise an exception.
def get_odd_number():
    try:
        num = int(input("Enter an odd number: "))
        if num % 2 == 0:
            raise ValueError("That is not an odd number!")
        print(f"Thank you! You entered the odd number: {num}")
    except ValueError as v:
      pass

In [ ]:
#Module 8 DA- Working with NumPy (python)

In [ ]:
#1.How to Creating a 3x3 Identity Matrix with Float Data Type?
import numpy as np

identity_matrix = np.identity(3, dtype=float)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#2.Create a 1D Array with Random Values between 0 and 1.
array_ad = np.random.rand(5)
print(array_1d)

[0.32050908 0.86011724 0.18048231 0.40397236 0.1586721 ]


In [ ]:
#3.Create a 2D Array with Random Integer Values.
import numpy as np

array_2d = np.random.randint(0, 10, size=(3, 4))

print(array_2d)

[[0 9 5 9]
 [4 0 1 6]
 [1 0 2 6]]


In [ ]:
#4.Creating an Array Using a Custom Function.
import numpy as np

def custom_func(i, j):
    return i + j

array_func = np.fromfunction(custom_func, (3, 4), dtype=int)

print(array_func)


[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


In [ ]:
#5.Reshaping a 1D Array into a 2D Array

array_1d = np.arange(12)
array_2d = array_1d.reshape(3, 4)

print(array_1d)

print(array_2d)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#6.How to Creating a 3x3 Array of Ones
ones_array = np.ones((3, 3))

print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#7.How to get the common items between two pythons
#NumPy? Input:
#a = np. array ([1,2,3,2,3,4,3,4,5,6])
#b = np. array ([7,2,10,2,7,4,9,4,9,8])
#Expected Output:
#array ([2, 4])
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

common_items = np.intersect1d(a, b)

print(common_items)

[2 4]


In [ ]:
#8. From array a remove all items present in
#array b Input:
#a = np. array ([1,2,3,4,5])
#b = np. array ([5,6,7,8,9])
#Expected Output:
#array ([1,2,3,4]

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

result = np.setdiff1d(a, b)

print(result)

[1 2 3 4]


In [ ]:
#9. Limit the number of items printed in python NumPy array a to a maximum of
#6 elements.
#a = np. arrange (15)
#Expected Output:
#array ([ 0, 1, 2, ..., 12, 13, 14]

a = np.arange(15)

np.set_printoptions(threshold=6)

print(a)

[ 0  1  2 ... 12 13 14]


In [ ]:
#10.Drop all nan values from a 1D NumPy
#array Input:
#np. array ([1,2,3, np.nan,5,6,7, np.nan])
#Desired Output:
#array ([ 1., 2., 3., 5., 6., 7.])

a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])

cleaned_array = a[~np.isnan(a)]

print(cleaned_array)

[1. 2. 3. 5. 6. 7.]


In [ ]:
#11.Create a 1D NumPy array of the first 20 natural numbers and a
#2D NumPy array of shape (4, 5) with values ranging from 1 to 20.

array_1d = np.arange(1, 21)

array_2d = array_1d.reshape(4, 5)

print(array_1d)

print(array_2d)

[ 1  2  3 ... 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
#12.Given a 3D NumPy array of shape (2, 3, 4), find its shape, size,
#number of dimensions, and data type. Change its data type to float64 and verify
#the change.


array_3d = np.arange(24).reshape(2, 3, 4)

print("Shape:", array_3d.shape)
print("Size:", array_3d.size)
print("Dimensions:", array_3d.ndim)
print("Data type:", array_3d.dtype)

array_3d = array_3d.astype(np.float64)

print("New data type:", array_3d.dtype)

Shape: (2, 3, 4)
Size: 24
Dimensions: 3
Data type: int64
New data type: float64


In [ ]:
#13.Reshape a 1D array of 12 elements into a 3x4 2D array and then
#flatten it back into a 1D array using ravel (). Verify that the flattened array
#matches the original.

original_array = np.arange(12)

reshaped_array = original_array.reshape(3, 4)

flattened_array = reshaped_array.ravel()

is_equal = np.array_equal(original_array, flattened_array)


print("Original 1D Array:")
print(original_array)

print("\nReshaped 2D Array (3x4):")
print(reshaped_array)

print("\nFlattened Array:")
print(flattened_array)

print("\nDoes flattened array match original?:", is_equal)

Original 1D Array:
[ 0  1  2 ...  9 10 11]

Reshaped 2D Array (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened Array:
[ 0  1  2 ...  9 10 11]

Does flattened array match original?: True


In [ ]:
#14. Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4,
#5, 6]), perform element-wise addition, subtraction, multiplication, and
#division. Explain the behavior when dividing by zero.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

add_result = a + b
sub_result = a - b
mul_result = a * b
div_result = a / b

print("Addition:      ", add_result)
print("Subtraction:   ", sub_result)
print("Multiplication:", mul_result)
print("Division:      ", div_result)

Addition:       [5 7 9]
Subtraction:    [-3 -3 -3]
Multiplication: [ 4 10 18]
Division:       [0.25 0.4  0.5 ]


In [ ]:
#15. Create a 2D array of shape (3, 1) and a 1D array of length 3. Perform
#element-wise addition using broadcasting. Explain how broadcasting rules apply
#in this scenario.

a = np.array([[1], [2], [3]])

b = np.array([10, 20, 30])

result = a + b

print("2D array a (shape (3,1)):\n", a)
print("\n1D array b (length 3):\n", b)
print("\nResult of a + b:\n", result)


2D array a (shape (3,1)):
 [[1]
 [2]
 [3]]

1D array b (length 3):
 [10 20 30]

Result of a + b:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
#16. Generate a random 2D array of integers between 0 and 10. Use
#Page 24 of 28
#conditional operators to create a Boolean mask identifying elements greater than

array = np.random.randint(0, 11, size=(4, 5))

mask = array > 5

array[mask] = 5
print("Modified Array:")
print(array)


Modified Array:
[[0 5 0 5 3]
 [5 5 5 5 1]
 [5 4 4 5 5]
 [2 1 5 5 1]]


In [ ]:
#17.Given a 4x4 array of random integers, use indexing and slicing
#to extract:
#o The entire second row
#o The last column
#o The subarray consisting of the first two rows and first two column

array = np.random.randint(0, 10, size=(4, 4))

print("Original 4x4 Array:\n", array)

second_row = array[1, :]

last_column = array[:, -1]

subarray = array[:2, :2]

print("\nSecond Row:\n", second_row)
print("\nLast Column:\n", last_column)
print("\nSubarray (First 2 rows and 2 columns):\n", subarray)

Original 4x4 Array:
 [[7 1 1 5]
 [2 8 6 6]
 [7 3 5 9]
 [7 9 3 4]]

Second Row:
 [2 8 6 6]

Last Column:
 [5 6 9 4]

Subarray (First 2 rows and 2 columns):
 [[7 1]
 [2 8]]


In [ ]:
#18.Describe a practical example where NumPy can be used in EDA,
#AI, ML, and DL, and implement a NumPy solution for a simple task in each
#area.
sales = np.array([250, 300, 270, 310, 265, 290, 305])

print("Mean sales:", np.mean(sales))
print("Median sales:", np.median(sales))
print("Standard Deviation:", np.std(sales))

Mean sales: 284.2857142857143
Median sales: 290.0
Standard Deviation: 21.11677928442069


In [2]:
#19.Create a random 4x4 matrix and use NumPy to compute its eigenvalues and eigenvectors. Verify the eigenvalues by reconstructing the matrix.
import numpy as np

np.random.seed(0)
A = np.random.rand(4, 4)
print("Original Matrix A:\n", A)

eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

D = np.diag(eigenvalues)
V = eigenvectors
V_inv = np.linalg.inv(V)
A_reconstructed = V @ D @ V_inv

print("\nReconstructed Matrix A from Eigen Decomposition:\n", A_reconstructed)

is_close = np.allclose(A, A_reconstructed)
print("\nReconstruction successful:", is_close)

Original Matrix A:
 [[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]

Eigenvalues:
 [ 2.28158836 -0.5139378  -0.22422772  0.53013911]

Eigenvectors:
 [[ 0.52354106 -0.10090767  0.5285094  -0.1584302 ]
 [ 0.49196427  0.55773542 -0.43250014  0.36386336]
 [ 0.59384504  0.23102177 -0.57357157 -0.81262442]
 [ 0.36224851 -0.79080831  0.45236832  0.42678435]]

Reconstructed Matrix A from Eigen Decomposition:
 [[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]

Reconstruction successful: True


In [3]:
#20.Create a 1D array of 27 elements and reshape it into a 3x3x3 3D array. Flatten it back into a 1D array and compare the flattened array with the original.

original_array = np.arange(27)
print("Original 1D Array:\n", original_array)

array_3d = original_array.reshape((3, 3, 3))
print("\nReshaped 3D Array (3x3x3):\n", array_3d)

flattened_array = array_3d.flatten()
print("\nFlattened Array:\n", flattened_array)

comparison = np.array_equal(original_array, flattened_array)
print("\nAre the original and flattened arrays equal?:", comparison)

Original 1D Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]

Reshaped 3D Array (3x3x3):
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Flattened Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]

Are the original and flattened arrays equal?: True


In [4]:
#21. Perform matrix multiplication of two 2D arrays using np.dot () and @. Compare the results and performance of both methods using a large dataset.

import numpy as np
import time

np.random.seed(42)
A = np.random.rand(1000, 1000)
B = np.random.rand(1000, 1000)

start_dot = time.time()
result_dot = np.dot(A, B)
end_dot = time.time()
time_dot = end_dot - start_dot
print("Time using np.dot():", time_dot, "seconds")

start_at = time.time()
result_at = A @ B
end_at = time.time()
time_at = end_at - start_at
print("Time using @ operator:", time_at, "seconds")

are_equal = np.allclose(result_dot, result_at)
print("Are results equal?:", are_equal)

Time using np.dot(): 0.1198279857635498 seconds
Time using @ operator: 0.1205599308013916 seconds
Are results equal?: True


In [7]:
#22. Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4, 1). Perform an element-wise operation using broadcasting and explain the result. Use np. new axis to achieve the same result without broadcasting.

A = np.array([[[1, 2, 3, 4]], [[5, 6, 7, 8]]])
print("3D Array A (shape {}):\n{}".format(A.shape, A))

B = np.array([[10], [20], [30], [40]])
print("\n2D Array B (shape {}):\n{}".format(B.shape, B))


result_broadcast = A + B.T
print("\nResult using broadcasting (A + B.T):\n", result_broadcast)

B_expanded = B.T[np.newaxis, :, :]
A_expanded = A
result_manual = A_expanded + B_expanded
print("\nResult using np.newaxis:\n", result_manual)

print("\nAre both results equal?:", np.array_equal(result_broadcast, result_manual))


3D Array A (shape (2, 1, 4)):
[[[1 2 3 4]]

 [[5 6 7 8]]]

2D Array B (shape (4, 1)):
[[10]
 [20]
 [30]
 [40]]

Result using broadcasting (A + B.T):
 [[[11 22 33 44]]

 [[15 26 37 48]]]

Result using np.newaxis:
 [[[11 22 33 44]]

 [[15 26 37 48]]]

Are both results equal?: True


In [8]:
#23. Generate a 2D array of random floats between 0 and 1. Use conditional operators to create a Boolean mask for values less than 0.5. Replace these values with their squares and leave the rest unchanged.

np.random.seed(0)
arr = np.random.rand(4, 5)
print("Original Array:\n", arr)

mask = arr < 0.5
print("\nBoolean Mask (True for values < 0.5):\n", mask)

arr[mask] = arr[mask] ** 2
print("\nModified Array (values < 0.5 squared):\n", arr)

Original Array:
 [[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]]

Boolean Mask (True for values < 0.5):
 [[False False False False  True]
 [False  True False False  True]
 [False False False False  True]
 [ True  True False False False]]

Modified Array (values < 0.5 squared):
 [[5.48813504e-01 7.15189366e-01 6.02763376e-01 5.44883183e-01
  1.79483389e-01]
 [6.45894113e-01 1.91482567e-01 8.91773001e-01 9.63662761e-01
  1.47027398e-01]
 [7.91725038e-01 5.28894920e-01 5.68044561e-01 9.25596638e-01
  5.04612156e-03]
 [7.59151487e-03 4.08783595e-04 8.32619846e-01 7.78156751e-01
  8.70012148e-01]]


In [9]:
#24. Given a 5x5 array of sequential integers, use slicing to:
#o Extract the diagonal elements
#o Replace the elements of the middle row with zeros
#o Flip the array vertically and horizontally

arr = np.arange(1, 26).reshape(5, 5)
print("Original 5x5 Array:\n", arr)

diagonal = np.diag(arr)
print("\nDiagonal Elements:\n", diagonal)

arr[2, :] = 0
print("\nArray After Replacing Middle Row with Zeros:\n", arr)

vertical_flip = arr[::-1, :]
print("\nVertically Flipped Array:\n", vertical_flip)

horizontal_flip = arr[:, ::-1]
print("\nHorizontally Flipped Array:\n", horizontal_flip)

Original 5x5 Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Diagonal Elements:
 [ 1  7 13 19 25]

Array After Replacing Middle Row with Zeros:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 0  0  0  0  0]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Vertically Flipped Array:
 [[21 22 23 24 25]
 [16 17 18 19 20]
 [ 0  0  0  0  0]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]

Horizontally Flipped Array:
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [ 0  0  0  0  0]
 [20 19 18 17 16]
 [25 24 23 22 21]]


In [10]:
#25. Create a 4D array of shape (2, 3, 4, 5) with random integers. Use advanced slicing to extract a subarray and compute the mean along a specified axis.

np.random.seed(0)
arr = np.random.randint(0, 100, size=(2, 3, 4, 5))
print("Original 4D Array shape:", arr.shape)

subarray = arr[0, :, 0:2, 2:]
print("\nSubarray shape (from slicing [0, :, 0:2, 2:]):", subarray.shape)
print("Subarray:\n", subarray)

mean_along_last_axis = np.mean(subarray, axis=-1)
print("\nMean along last axis (axis=-1):\n", mean_along_last_axis)


Original 4D Array shape: (2, 3, 4, 5)

Subarray shape (from slicing [0, :, 0:2, 2:]): (3, 2, 3)
Subarray:
 [[[64 67 67]
  [21 36 87]]

 [[25 77 72]
  [80 69 79]]

 [[65  9 57]
  [74 23 35]]]

Mean along last axis (axis=-1):
 [[66.         48.        ]
 [58.         76.        ]
 [43.66666667 44.        ]]


In [11]:
#26. Given an array of shape (10, 20), reshape it to (20, 10) and (5, 40). Discuss the impact on the array's shape, size, and dimensionality.


arr = np.arange(200).reshape(10, 20)
print("Original shape:", arr.shape)

reshaped_1 = arr.reshape(20, 10)
print("Reshaped to (20, 10):", reshaped_1.shape)

reshaped_2 = arr.reshape(5, 40)
print("Reshaped to (5, 40):", reshaped_2.shape)

Original shape: (10, 20)
Reshaped to (20, 10): (20, 10)
Reshaped to (5, 40): (5, 40)


In [12]:
#27. Generate a large 2D array and demonstrate the use of np. reshape () and unravel () to manipulate its shape for various linear algebra operations.

array_2d = np.random.randint(1, 100, size=(100, 50))
print("Original Shape:", array_2d.shape)

reshaped_transposed = array_2d.reshape(50, 100)
print("Reshaped to:", reshaped_transposed.shape)

flattened = array_2d.ravel()
print("Flattened shape:", flattened.shape)

flat_index_max = np.argmax(flattened)
row, col = np.unravel_index(flat_index_max, array_2d.shape)
print(f"Max value is at flat index {flat_index_max} → position ({row}, {col})")

dot_product = np.dot(array_2d[:10, :], reshaped_transposed[:, :10])
print("\nDot product shape (10x10):", dot_product.shape)


Original Shape: (100, 50)
Reshaped to: (50, 100)
Flattened shape: (5000,)
Max value is at flat index 7 → position (0, 7)

Dot product shape (10x10): (10, 10)


In [13]:
#28. Given a 6x6 matrix, use advanced indexing and slicing to extract the upper triangular part of the matrix and set the lower triangular part to zero. Verify the result.

np.random.seed(0)
matrix = np.random.randint(1, 100, size=(6, 6))
print("Original 6x6 Matrix:\n", matrix)

upper_tri = np.triu(matrix)
print("\nUpper Triangular Matrix (Lower part zeroed):\n", upper_tri)

is_lower_zero = np.allclose(np.tril(upper_tri, -1), 0)
print("\nLower triangle is zero:", is_lower_zero)


Original 6x6 Matrix:
 [[45 48 65 68 68 10]
 [84 22 37 88 71 89]
 [89 13 59 66 40 88]
 [47 89 82 38 26 78]
 [73 10 21 81 70 80]
 [48 65 83 89 50 30]]

Upper Triangular Matrix (Lower part zeroed):
 [[45 48 65 68 68 10]
 [ 0 22 37 88 71 89]
 [ 0  0 59 66 40 88]
 [ 0  0  0 38 26 78]
 [ 0  0  0  0 70 80]
 [ 0  0  0  0  0 30]]

Lower triangle is zero: True


In [ ]:
#Module 9) DA- Working with Pandas (python)

In [ ]:
import pandas as pd

#1. Create a Series with three different colors?
colors = pd.Series(['Red', 'Green', 'Blue'])
print(colors)


0      Red
1    Green
2     Blue
dtype: object


In [ ]:
#2. View the series of different colors?
colors = pd.Series(['Yellow', 'Black', 'Sky'])
print(colors)


0    Yellow
1     Black
2       Sky
dtype: object


In [ ]:
#3. Create a series of three different car types and view it?
car_types = pd.Series(['Sedan', 'SUV', 'Hatchback'])
print(car_types)


0        Sedan
1          SUV
2    Hatchback
dtype: object


In [ ]:
#4. Combine the Series of cars and colors into a Data Frame?
car_company = pd.Series(['Mahindra','Maruti Suzuki','Tata Moters','Toyota',"Hyundai","Ford","Nissan",'Chevrolet'])
colors = pd.Series(['Brown','Grey','White','Yellow',"Black",'Sky','Red','Green'])
car_data = pd.DataFrame({
    'Car_Company' : car_company,
     'Colors' : colors
})
print(car_data)

     Car_Company  Colors
0       Mahindra   Brown
1  Maruti Suzuki    Grey
2    Tata Moters   White
3         Toyota  Yellow
4        Hyundai   Black
5           Ford     Sky
6         Nissan     Red
7      Chevrolet   Green


In [ ]:
#5.Find the different datatypes of the car data Data Frame?
print(car_data.dtypes)

Car_Company    object
Colors         object
dtype: object


In [ ]:
#6.Describe your current car sales Data Frame using describe () ?
print(car_data.describe())

       Car_Company Colors
count            8      8
unique           8      8
top       Mahindra  Brown
freq             1      1


In [ ]:
#7.Get information about your Data Frame using info ()
print(car_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Car_Company  8 non-null      object
 1   Colors       8 non-null      object
dtypes: object(2)
memory usage: 260.0+ bytes
None


In [ ]:
#8. Create a Series of different numbers and find the mean of them
x = pd.Series([1,2,3,4,5,6,7,8,9,10])
print(x.mean())

5.5


In [ ]:
#9. Create a Series of different numbers and find the sum of them ?
Y = pd.Series([10,20,30,40,50])
print(Y.sum())

150


In [ ]:
#10. List out all the column names of the car sales Data Frame ?
Column_name = car_data.columns.to_list()
print(Column_name)

['Car_Company', 'Colors']


In [ ]:
#11. Find the length of the car sales Data Frame ?
length = len(car_data)
print(length)

8


In [ ]:
#12. Show the first 5 rows of the car sales Data Frame ?
Row = car_data.head(5)
print(Row)

     Car_Company  Colors
0       Mahindra   Brown
1  Maruti Suzuki    Grey
2    Tata Moters   White
3         Toyota  Yellow
4        Hyundai   Black


In [ ]:
#13. Show the first 7 rows of the car sales Data Frame ?
Row1 = car_data.head(7)
print(Row1)

     Car_Company  Colors
0       Mahindra   Brown
1  Maruti Suzuki    Grey
2    Tata Moters   White
3         Toyota  Yellow
4        Hyundai   Black
5           Ford     Sky
6         Nissan     Red


In [ ]:
#14.Show the bottom 5 rows of the car sales Data Frame ?
Row2 = car_data.tail(5)
print(Row2)

  Car_Company  Colors
3      Toyota  Yellow
4     Hyundai   Black
5        Ford     Sky
6      Nissan     Red
7   Chevrolet   Green


In [ ]:
#15. Use. loc to select the row at index 3 of the car sales Data Frame ?
Loc_3 = car_data.loc[3]
print(Loc_3)

Car_Company    Toyota
Colors         Yellow
Name: 3, dtype: object


In [ ]:
#16. Use. iloc to select the row at position 3 of the car sales Data Frame ?
Iloc_3 = car_data.iloc[3]
print(Iloc_3)

Car_Company    Toyota
Colors         Yellow
Name: 3, dtype: object


In [ ]:
#17. Create a crosstab of the Make and Doors columns. ?
data = {
    'Make': ['Toyota', 'Honda', 'Ford', 'Toyota', 'Ford', 'Honda', 'Ford'],
    'Doors': [4, 4, 2, 2, 4, 2, 2]
    }
car_data = pd.DataFrame(data)

crosstab_result = pd.crosstab(car_data['Make'], car_data['Doors'])
print(crosstab_result)

Doors   2  4
Make        
Ford    2  1
Honda   1  1
Toyota  1  1
